<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class Voto extends Model{

    public function electors(){
        $this->hasMany('App\Models\Elector');
    }
}
